### ISSUE TITLE
改名物品跨服后乱码

### ISSUE THREAD

**Issue by leitingsd** [KenRouKoro/InterconnectionPlayer#1]
通过铁砧改名后的物品/潜影盒在跨服同步数据后名称变为乱码，如图
![$3_MH8)F$)GBM8FFY) D0_R](https://github.com/KenRouKoro/InterconnectionPlayer/assets/47239222/98effdb0-4454-4a7f-bede-aee83eb4f278)

**Comment by KenRouKoro** [comment]
emmm我测试的时候没有问题，能方便提供一下你进行的操作和服务端版本吗
![image](https://github.com/KenRouKoro/InterconnectionPlayer/assets/21196863/3212e5ea-421f-41b8-b734-f00da9a1304b)
这个是fabric与paper两端同步铁砧重命名的样子

**Comment by leitingsd** [comment]
Velocity下Fabric与Arclight(Fabric)两个子服 
Fabric 0.15.7
Arclight-fabric-1.20.4-1.0.3
使用铁砧重命名物品包括“装有物品的潜影盒”“附魔工具”“未附魔工具”“物品”
均有概率跨服同步背包后出现名字乱码

**Comment by KenRouKoro** [comment]
我不能确保Arclight是否能与我的mod兼容，因为我使用的是完全原版的物品NBT二进制序列化与反序列化的方法（NBTIO），Arclight很有可能影响这一部分，毕竟它属于混合端的范围，我现在已知的是在NeoForge，Fabric，Paper系这三类服务端并没有修改MJ的这一部分。而且根据你的问题推断，是在Text tag转Component （mojmap）上有问题，但在此处我是完全使用原版的方法，你可以尝试直接将fabric的玩家存档在Arclight中加载，或者反过来，可能也会出现与现在类似的问题。

**Comment by leitingsd** [comment]
先问一下，您是用Fabric还是Paper作为中央节点？
这边测试了Fabric、Arclight、LeaveMC与Paper，测试了两种环境：Arclight作为中央节点与Fabric作为中央节点；
多种情况：在Fabric作为中央节点情况下，仅有Fabric与LeaveMC、Arclight与LeaveMC、Fabric与Arlight、Fabric与Paper四种情况；
在Arclight作为中央节点情况下，Fabric与LeaveMC、Arclight与LeaveMC、Fabric与Arlight三种情况；
即使是只保留Paper与Fabric两个子服务器运行，Fabric作为中央节点，确保数据不与Arclight/LeaveMC同步的情况下，仍然出现数据标签叠加问题，每跨一次服叠加一个text标签，如图。
![P`B)7G_HO) })7AC0AONO$A](https://github.com/KenRouKoro/InterconnectionPlayer/assets/47239222/4580f5ae-2c34-41e9-b888-f57605241feb)

有没有可能是对中央节点有核心要求，或者是Velocity的影响？
上述测试环境均是在以Velocity作为群组服核心的情况下。

附·核心版本数据：
Velocity：Velocity 3.3.0-SNAPSHOT Build#370
Paper：1.20.4 Build#450
LeaveMC：1.20.4 Build#190
Arclight：Arclight-fabric-1.20.4-1.0.3

**Comment by leitingsd** [comment]
另：如您图所示，最开始也是会出现（”内容“）多个双引号，跨多几次就会叠text标签。
即使物品一开始命名就没有双引号。
例：物品一开始命名为 1 ，跨服后变成 "1" ，再跨几次就会开始叠加text标签（如上图示）

**Comment by KenRouKoro** [comment]
中央节点和传输无关，它只用于组网，其次和跨服端无关，数据不经过跨服端。你可以发一下玩家dat我看看具体nbt标签情况。

**Comment by KenRouKoro** [comment]
我可以简单描述一下工作流程，首先mod会使用原版方法加载玩家dat数据，这和原版加载玩家数据是一致的，然后直接使用加载后的nbt数据复制一份后去掉不需要的部分（但玩家背包是一个完整的listtag，我没有操作里面的内容），然后直接传输到目标服务器，目标服务器直接将对应的nbt传入player的对应load方法

**Comment by leitingsd** [comment]
[d42338e5-e42d-4b8b-a73e-1092399888a5.zip](https://github.com/KenRouKoro/InterconnectionPlayer/files/14614297/d42338e5-e42d-4b8b-a73e-1092399888a5.zip)

**Comment by leitingsd** [comment]
另附一段来自控制台的有关数据包长度过长的输出：
[17:36:03] [Server thread/INFO]: Leitingsd[/127.0.0.1:65041] logged in with entity id 1783 at (-824.2393576251799, 102.8681430633933, -1206.754732506092)
[17:36:03] [Server thread/INFO]: Leitingsd joined the game
[17:36:03] [Netty Server IO #6/INFO]: CarpetNetworkProtocolRewriter rewrite start, target=V2
[17:36:03] [Netty Server IO #6/INFO]: UniversalCarpetPayload read V1 failed, err=java.lang.Exception: unknown action 10
[17:36:03] [Netty Server IO #6/INFO]: UniversalCarpetPayload read V2 success, nbt={420:"1.4.128+v231205"}
[17:36:04] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:04] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:04] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:04] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:04] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:04] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:04] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:04] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:04] [Server thread/INFO]: Player Leitingsd joined with a matching carpet client
[17:36:04] [Netty Server IO #6/ERROR]: Error receiving packet 21
io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: encoded string ({"text":...\"}\"}"}) too long: 98401 bytes
        at net.minecraft.class_2540.method_10794(class_2540.java:563) ~[server-intermediary.jar:?]
        at net.minecraft.class_2540.method_10793(class_2540.java:604) ~[server-intermediary.jar:?]
        at net.minecraft.class_2653.method_11052(class_2653.java:36) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.method_10838(class_2545.java:47) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:15) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:321) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_52917(class_2535.java:316) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.UTFDataFormatException: encoded string ({"text":...\"}\"}"}) too long: 98401 bytes
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:369) ~[?:?]
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:333) ~[?:?]
        at io.netty.buffer.ByteBufOutputStream.writeUTF(ByteBufOutputStream.java:143) ~[netty-buffer-4.1.97.Final.jar:?]
        at net.minecraft.class_2519.method_10713(class_2519.java:83) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10555(class_2487.java:515) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10713(class_2487.java:193) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10555(class_2487.java:515) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10713(class_2487.java:193) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_52893(class_2507.java:152) ~[server-intermediary.jar:?]
        at net.minecraft.class_2540.method_10794(class_2540.java:561) ~[server-intermediary.jar:?]
        ... 26 more
[17:36:04] [Server thread/INFO]: Leitingsd lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: encoded string ({"text":...\"}\"}"}) too long: 98401 bytes
[17:36:04] [Server thread/INFO]: Leitingsd left the game
[17:36:04] [Server thread/ERROR]: Failed to write NBT String
java.io.UTFDataFormatException: encoded string ({"text":...\"}\"}"}) too long: 98401 bytes
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:369) ~[?:?]
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:333) ~[?:?]
        at net.minecraft.class_8941.writeUTF(class_8941.java:80) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507$class_9003.writeUTF(class_2507.java:202) ~[server-intermediary.jar:?]
        at net.minecraft.class_2519.method_10713(class_2519.java:83) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10555(class_2487.java:515) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10713(class_2487.java:193) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10555(class_2487.java:515) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10713(class_2487.java:193) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10555(class_2487.java:515) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10713(class_2487.java:193) ~[server-intermediary.jar:?]
        at net.minecraft.class_2499.method_10713(class_2499.java:150) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10555(class_2487.java:515) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10713(class_2487.java:193) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_10631(class_2507.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_55324(class_2507.java:168) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_10628(class_2507.java:113) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_10634(class_2507.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_30614(class_2507.java:67) ~[server-intermediary.jar:?]
        at net.minecraft.class_29.method_262(class_29.java:35) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14577(class_3324.java:359) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14611(class_3324.java:378) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_52415(class_3244.java:1215) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_10839(class_3244.java:1204) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10768(class_2535.java:618) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:189) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:36:04] [smart-socket:Thread-3/INFO]: 收到玩家数据请求，玩家UUID为：d42338e5-e42d-4b8b-a73e-1092399888a5
[17:36:07] [Server thread/INFO]: Leitingsd[/127.0.0.1:65044] logged in with entity id 1921 at (-824.2393576251799, 102.8681430633933, -1206.754732506092)
[17:36:07] [Server thread/INFO]: Leitingsd joined the game
[17:36:07] [Netty Server IO #7/INFO]: CarpetNetworkProtocolRewriter rewrite start, target=V2
[17:36:07] [Netty Server IO #7/INFO]: UniversalCarpetPayload read V1 failed, err=java.lang.Exception: unknown action 10
[17:36:07] [Netty Server IO #7/INFO]: UniversalCarpetPayload read V2 success, nbt={420:"1.4.128+v231205"}
[17:36:07] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:07] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:07] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:07] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:07] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:07] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:07] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:07] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:orange_shulker_box
[17:36:08] [Server thread/INFO]: Player Leitingsd joined with a matching carpet client
[17:36:08] [Server thread/INFO]: Syncmatica client joining with local version 0.3.11 and client version 0.3.11
[17:36:15] [Server thread/INFO]: Leitingsd lost connection: Disconnected
[17:36:15] [Server thread/INFO]: Leitingsd left the game

**Comment by leitingsd** [comment]
重新测试了一遍，删除了所有playerdata数据和存档数据；
paper与fabric双服务端，原物品在paper命名为 111 ，图一是从paper跨到fabric，图二是从fabric跨回paper，图三再次从paper跨到fabric：
![1](https://github.com/KenRouKoro/InterconnectionPlayer/assets/47239222/a5128ede-56ec-4582-90d1-0486180d0f0f)
![2](https://github.com/KenRouKoro/InterconnectionPlayer/assets/47239222/3eced6e9-eabc-4026-8252-cdd9c9fc0326)
![3](https://github.com/KenRouKoro/InterconnectionPlayer/assets/47239222/9d2f6478-82e9-4b1b-a88a-9fbd1aa18d26)
